// Generated by gencpp from file qb_device_srvs/InitializeDevice.msg
// DO NOT EDIT!


#ifndef QB_DEVICE_SRVS_MESSAGE_INITIALIZEDEVICE_H
#define QB_DEVICE_SRVS_MESSAGE_INITIALIZEDEVICE_H

#include <ros/service_traits.h>


#include <qb_device_srvs/InitializeDeviceRequest.h>
#include <qb_device_srvs/InitializeDeviceResponse.h>


namespace qb_device_srvs
{

struct InitializeDevice
{

typedef InitializeDeviceRequest Request;
typedef InitializeDeviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitializeDevice
} // namespace qb_device_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qb_device_srvs::InitializeDevice > {
  static const char* value()
  {
    return "c23409117bb3e9fa24111fdf884ca1f3";
  }

  static const char* value(const ::qb_device_srvs::InitializeDevice&) { return value(); }
};

template<>
struct DataType< ::qb_device_srvs::InitializeDevice > {
  static const char* value()
  {
    return "qb_device_srvs/InitializeDevice";
  }

  static const char* value(const ::qb_device_srvs::InitializeDevice&) { return value(); }
};


// service_traits::MD5Sum< ::qb_device_srvs::InitializeDeviceRequest> should match
// service_traits::MD5Sum< ::qb_device_srvs::InitializeDevice >
template<>
struct MD5Sum< ::qb_device_srvs::InitializeDeviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qb_device_srvs::InitializeDevice >::value();
  }
  static const char* value(const ::qb_device_srvs::InitializeDeviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qb_device_srvs::InitializeDeviceRequest> should match
// service_traits::DataType< ::qb_device_srvs::InitializeDevice >
template<>
struct DataType< ::qb_device_srvs::InitializeDeviceRequest>
{
  static const char* value()
  {
    return DataType< ::qb_device_srvs::InitializeDevice >::value();
  }
  static const char* value(const ::qb_device_srvs::InitializeDeviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qb_device_srvs::InitializeDeviceResponse> should match
// service_traits::MD5Sum< ::qb_device_srvs::InitializeDevice >
template<>
struct MD5Sum< ::qb_device_srvs::InitializeDeviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qb_device_srvs::InitializeDevice >::value();
  }
  static const char* value(const ::qb_device_srvs::InitializeDeviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qb_device_srvs::InitializeDeviceResponse> should match
// service_traits::DataType< ::qb_device_srvs::InitializeDevice >
template<>
struct DataType< ::qb_device_srvs::InitializeDeviceResponse>
{
  static const char* value()
  {
    return DataType< ::qb_device_srvs::InitializeDevice >::value();
  }
  static const char* value(const ::qb_device_srvs::InitializeDeviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QB_DEVICE_SRVS_MESSAGE_INITIALIZEDEVICE_H
