// Generated by gencpp from file qb_device_srvs/SetCommands.msg
// DO NOT EDIT!


#ifndef QB_DEVICE_SRVS_MESSAGE_SETCOMMANDS_H
#define QB_DEVICE_SRVS_MESSAGE_SETCOMMANDS_H

#include <ros/service_traits.h>


#include <qb_device_srvs/SetCommandsRequest.h>
#include <qb_device_srvs/SetCommandsResponse.h>


namespace qb_device_srvs
{

struct SetCommands
{

typedef SetCommandsRequest Request;
typedef SetCommandsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCommands
} // namespace qb_device_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qb_device_srvs::SetCommands > {
  static const char* value()
  {
    return "2a24c554c16e33a4da324c504c12f0f4";
  }

  static const char* value(const ::qb_device_srvs::SetCommands&) { return value(); }
};

template<>
struct DataType< ::qb_device_srvs::SetCommands > {
  static const char* value()
  {
    return "qb_device_srvs/SetCommands";
  }

  static const char* value(const ::qb_device_srvs::SetCommands&) { return value(); }
};


// service_traits::MD5Sum< ::qb_device_srvs::SetCommandsRequest> should match
// service_traits::MD5Sum< ::qb_device_srvs::SetCommands >
template<>
struct MD5Sum< ::qb_device_srvs::SetCommandsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qb_device_srvs::SetCommands >::value();
  }
  static const char* value(const ::qb_device_srvs::SetCommandsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qb_device_srvs::SetCommandsRequest> should match
// service_traits::DataType< ::qb_device_srvs::SetCommands >
template<>
struct DataType< ::qb_device_srvs::SetCommandsRequest>
{
  static const char* value()
  {
    return DataType< ::qb_device_srvs::SetCommands >::value();
  }
  static const char* value(const ::qb_device_srvs::SetCommandsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qb_device_srvs::SetCommandsResponse> should match
// service_traits::MD5Sum< ::qb_device_srvs::SetCommands >
template<>
struct MD5Sum< ::qb_device_srvs::SetCommandsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qb_device_srvs::SetCommands >::value();
  }
  static const char* value(const ::qb_device_srvs::SetCommandsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qb_device_srvs::SetCommandsResponse> should match
// service_traits::DataType< ::qb_device_srvs::SetCommands >
template<>
struct DataType< ::qb_device_srvs::SetCommandsResponse>
{
  static const char* value()
  {
    return DataType< ::qb_device_srvs::SetCommands >::value();
  }
  static const char* value(const ::qb_device_srvs::SetCommandsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QB_DEVICE_SRVS_MESSAGE_SETCOMMANDS_H
