// Generated by gencpp from file qb_device_srvs/SetControlMode.msg
// DO NOT EDIT!


#ifndef QB_DEVICE_SRVS_MESSAGE_SETCONTROLMODE_H
#define QB_DEVICE_SRVS_MESSAGE_SETCONTROLMODE_H

#include <ros/service_traits.h>


#include <qb_device_srvs/SetControlModeRequest.h>
#include <qb_device_srvs/SetControlModeResponse.h>


namespace qb_device_srvs
{

struct SetControlMode
{

typedef SetControlModeRequest Request;
typedef SetControlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetControlMode
} // namespace qb_device_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qb_device_srvs::SetControlMode > {
  static const char* value()
  {
    return "f6dd4c28fb851ba56deb138366053217";
  }

  static const char* value(const ::qb_device_srvs::SetControlMode&) { return value(); }
};

template<>
struct DataType< ::qb_device_srvs::SetControlMode > {
  static const char* value()
  {
    return "qb_device_srvs/SetControlMode";
  }

  static const char* value(const ::qb_device_srvs::SetControlMode&) { return value(); }
};


// service_traits::MD5Sum< ::qb_device_srvs::SetControlModeRequest> should match
// service_traits::MD5Sum< ::qb_device_srvs::SetControlMode >
template<>
struct MD5Sum< ::qb_device_srvs::SetControlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qb_device_srvs::SetControlMode >::value();
  }
  static const char* value(const ::qb_device_srvs::SetControlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qb_device_srvs::SetControlModeRequest> should match
// service_traits::DataType< ::qb_device_srvs::SetControlMode >
template<>
struct DataType< ::qb_device_srvs::SetControlModeRequest>
{
  static const char* value()
  {
    return DataType< ::qb_device_srvs::SetControlMode >::value();
  }
  static const char* value(const ::qb_device_srvs::SetControlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qb_device_srvs::SetControlModeResponse> should match
// service_traits::MD5Sum< ::qb_device_srvs::SetControlMode >
template<>
struct MD5Sum< ::qb_device_srvs::SetControlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qb_device_srvs::SetControlMode >::value();
  }
  static const char* value(const ::qb_device_srvs::SetControlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qb_device_srvs::SetControlModeResponse> should match
// service_traits::DataType< ::qb_device_srvs::SetControlMode >
template<>
struct DataType< ::qb_device_srvs::SetControlModeResponse>
{
  static const char* value()
  {
    return DataType< ::qb_device_srvs::SetControlMode >::value();
  }
  static const char* value(const ::qb_device_srvs::SetControlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QB_DEVICE_SRVS_MESSAGE_SETCONTROLMODE_H
