// Generated by gencpp from file qb_device_srvs/SetPID.msg
// DO NOT EDIT!


#ifndef QB_DEVICE_SRVS_MESSAGE_SETPID_H
#define QB_DEVICE_SRVS_MESSAGE_SETPID_H

#include <ros/service_traits.h>


#include <qb_device_srvs/SetPIDRequest.h>
#include <qb_device_srvs/SetPIDResponse.h>


namespace qb_device_srvs
{

struct SetPID
{

typedef SetPIDRequest Request;
typedef SetPIDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPID
} // namespace qb_device_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qb_device_srvs::SetPID > {
  static const char* value()
  {
    return "924f2bcd17c4f9d95c42467a96352ac1";
  }

  static const char* value(const ::qb_device_srvs::SetPID&) { return value(); }
};

template<>
struct DataType< ::qb_device_srvs::SetPID > {
  static const char* value()
  {
    return "qb_device_srvs/SetPID";
  }

  static const char* value(const ::qb_device_srvs::SetPID&) { return value(); }
};


// service_traits::MD5Sum< ::qb_device_srvs::SetPIDRequest> should match
// service_traits::MD5Sum< ::qb_device_srvs::SetPID >
template<>
struct MD5Sum< ::qb_device_srvs::SetPIDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qb_device_srvs::SetPID >::value();
  }
  static const char* value(const ::qb_device_srvs::SetPIDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qb_device_srvs::SetPIDRequest> should match
// service_traits::DataType< ::qb_device_srvs::SetPID >
template<>
struct DataType< ::qb_device_srvs::SetPIDRequest>
{
  static const char* value()
  {
    return DataType< ::qb_device_srvs::SetPID >::value();
  }
  static const char* value(const ::qb_device_srvs::SetPIDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qb_device_srvs::SetPIDResponse> should match
// service_traits::MD5Sum< ::qb_device_srvs::SetPID >
template<>
struct MD5Sum< ::qb_device_srvs::SetPIDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qb_device_srvs::SetPID >::value();
  }
  static const char* value(const ::qb_device_srvs::SetPIDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qb_device_srvs::SetPIDResponse> should match
// service_traits::DataType< ::qb_device_srvs::SetPID >
template<>
struct DataType< ::qb_device_srvs::SetPIDResponse>
{
  static const char* value()
  {
    return DataType< ::qb_device_srvs::SetPID >::value();
  }
  static const char* value(const ::qb_device_srvs::SetPIDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QB_DEVICE_SRVS_MESSAGE_SETPID_H
