// Generated by gencpp from file qb_device_srvs/Trigger.msg
// DO NOT EDIT!


#ifndef QB_DEVICE_SRVS_MESSAGE_TRIGGER_H
#define QB_DEVICE_SRVS_MESSAGE_TRIGGER_H

#include <ros/service_traits.h>


#include <qb_device_srvs/TriggerRequest.h>
#include <qb_device_srvs/TriggerResponse.h>


namespace qb_device_srvs
{

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trigger
} // namespace qb_device_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qb_device_srvs::Trigger > {
  static const char* value()
  {
    return "d696ad9232824524315696c7565a79d7";
  }

  static const char* value(const ::qb_device_srvs::Trigger&) { return value(); }
};

template<>
struct DataType< ::qb_device_srvs::Trigger > {
  static const char* value()
  {
    return "qb_device_srvs/Trigger";
  }

  static const char* value(const ::qb_device_srvs::Trigger&) { return value(); }
};


// service_traits::MD5Sum< ::qb_device_srvs::TriggerRequest> should match
// service_traits::MD5Sum< ::qb_device_srvs::Trigger >
template<>
struct MD5Sum< ::qb_device_srvs::TriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qb_device_srvs::Trigger >::value();
  }
  static const char* value(const ::qb_device_srvs::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qb_device_srvs::TriggerRequest> should match
// service_traits::DataType< ::qb_device_srvs::Trigger >
template<>
struct DataType< ::qb_device_srvs::TriggerRequest>
{
  static const char* value()
  {
    return DataType< ::qb_device_srvs::Trigger >::value();
  }
  static const char* value(const ::qb_device_srvs::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qb_device_srvs::TriggerResponse> should match
// service_traits::MD5Sum< ::qb_device_srvs::Trigger >
template<>
struct MD5Sum< ::qb_device_srvs::TriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qb_device_srvs::Trigger >::value();
  }
  static const char* value(const ::qb_device_srvs::TriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qb_device_srvs::TriggerResponse> should match
// service_traits::DataType< ::qb_device_srvs::Trigger >
template<>
struct DataType< ::qb_device_srvs::TriggerResponse>
{
  static const char* value()
  {
    return DataType< ::qb_device_srvs::Trigger >::value();
  }
  static const char* value(const ::qb_device_srvs::TriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QB_DEVICE_SRVS_MESSAGE_TRIGGER_H
