// Generated by gencpp from file qb_device_msgs/ConnectionState.msg
// DO NOT EDIT!


#ifndef QB_DEVICE_MSGS_MESSAGE_CONNECTIONSTATE_H
#define QB_DEVICE_MSGS_MESSAGE_CONNECTIONSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <qb_device_msgs/DeviceConnectionInfo.h>

namespace qb_device_msgs
{
template <class ContainerAllocator>
struct ConnectionState_
{
  typedef ConnectionState_<ContainerAllocator> Type;

  ConnectionState_()
    : devices()  {
    }
  ConnectionState_(const ContainerAllocator& _alloc)
    : devices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::qb_device_msgs::DeviceConnectionInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::qb_device_msgs::DeviceConnectionInfo_<ContainerAllocator> >> _devices_type;
  _devices_type devices;





  typedef boost::shared_ptr< ::qb_device_msgs::ConnectionState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qb_device_msgs::ConnectionState_<ContainerAllocator> const> ConstPtr;

}; // struct ConnectionState_

typedef ::qb_device_msgs::ConnectionState_<std::allocator<void> > ConnectionState;

typedef boost::shared_ptr< ::qb_device_msgs::ConnectionState > ConnectionStatePtr;
typedef boost::shared_ptr< ::qb_device_msgs::ConnectionState const> ConnectionStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qb_device_msgs::ConnectionState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qb_device_msgs::ConnectionState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qb_device_msgs::ConnectionState_<ContainerAllocator1> & lhs, const ::qb_device_msgs::ConnectionState_<ContainerAllocator2> & rhs)
{
  return lhs.devices == rhs.devices;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qb_device_msgs::ConnectionState_<ContainerAllocator1> & lhs, const ::qb_device_msgs::ConnectionState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qb_device_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qb_device_msgs::ConnectionState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qb_device_msgs::ConnectionState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qb_device_msgs::ConnectionState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qb_device_msgs::ConnectionState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qb_device_msgs::ConnectionState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qb_device_msgs::ConnectionState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qb_device_msgs::ConnectionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fb8aec8a16b727f8528545cb7e04895";
  }

  static const char* value(const ::qb_device_msgs::ConnectionState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fb8aec8a16b727fULL;
  static const uint64_t static_value2 = 0x8528545cb7e04895ULL;
};

template<class ContainerAllocator>
struct DataType< ::qb_device_msgs::ConnectionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qb_device_msgs/ConnectionState";
  }

  static const char* value(const ::qb_device_msgs::ConnectionState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qb_device_msgs::ConnectionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Device-independent connection state message\n"
"\n"
"qb_device_msgs/DeviceConnectionInfo[] devices\n"
"================================================================================\n"
"MSG: qb_device_msgs/DeviceConnectionInfo\n"
"# Device-independent message that constains: \n"
"\n"
"int32 id           # device id;\n"
"bool is_active     # motor activation status;\n"
"string port        # serial port\n"
;
  }

  static const char* value(const ::qb_device_msgs::ConnectionState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qb_device_msgs::ConnectionState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.devices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConnectionState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qb_device_msgs::ConnectionState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qb_device_msgs::ConnectionState_<ContainerAllocator>& v)
  {
    s << indent << "devices[]" << std::endl;
    for (size_t i = 0; i < v.devices.size(); ++i)
    {
      s << indent << "  devices[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::qb_device_msgs::DeviceConnectionInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.devices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QB_DEVICE_MSGS_MESSAGE_CONNECTIONSTATE_H
