// Generated by gencpp from file qb_device_msgs/Info.msg
// DO NOT EDIT!


#ifndef QB_DEVICE_MSGS_MESSAGE_INFO_H
#define QB_DEVICE_MSGS_MESSAGE_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qb_device_msgs
{
template <class ContainerAllocator>
struct Info_
{
  typedef Info_<ContainerAllocator> Type;

  Info_()
    : id(0)
    , serial_port()
    , max_repeats(0)
    , get_positions(false)
    , get_currents(false)
    , get_distinct_packages(false)
    , set_commands(false)
    , set_commands_async(false)
    , position_limits()
    , encoder_resolutions()  {
    }
  Info_(const ContainerAllocator& _alloc)
    : id(0)
    , serial_port(_alloc)
    , max_repeats(0)
    , get_positions(false)
    , get_currents(false)
    , get_distinct_packages(false)
    , set_commands(false)
    , set_commands_async(false)
    , position_limits(_alloc)
    , encoder_resolutions(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _serial_port_type;
  _serial_port_type serial_port;

   typedef int32_t _max_repeats_type;
  _max_repeats_type max_repeats;

   typedef uint8_t _get_positions_type;
  _get_positions_type get_positions;

   typedef uint8_t _get_currents_type;
  _get_currents_type get_currents;

   typedef uint8_t _get_distinct_packages_type;
  _get_distinct_packages_type get_distinct_packages;

   typedef uint8_t _set_commands_type;
  _set_commands_type set_commands;

   typedef uint8_t _set_commands_async_type;
  _set_commands_async_type set_commands_async;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _position_limits_type;
  _position_limits_type position_limits;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _encoder_resolutions_type;
  _encoder_resolutions_type encoder_resolutions;





  typedef boost::shared_ptr< ::qb_device_msgs::Info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qb_device_msgs::Info_<ContainerAllocator> const> ConstPtr;

}; // struct Info_

typedef ::qb_device_msgs::Info_<std::allocator<void> > Info;

typedef boost::shared_ptr< ::qb_device_msgs::Info > InfoPtr;
typedef boost::shared_ptr< ::qb_device_msgs::Info const> InfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qb_device_msgs::Info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qb_device_msgs::Info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qb_device_msgs::Info_<ContainerAllocator1> & lhs, const ::qb_device_msgs::Info_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.serial_port == rhs.serial_port &&
    lhs.max_repeats == rhs.max_repeats &&
    lhs.get_positions == rhs.get_positions &&
    lhs.get_currents == rhs.get_currents &&
    lhs.get_distinct_packages == rhs.get_distinct_packages &&
    lhs.set_commands == rhs.set_commands &&
    lhs.set_commands_async == rhs.set_commands_async &&
    lhs.position_limits == rhs.position_limits &&
    lhs.encoder_resolutions == rhs.encoder_resolutions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qb_device_msgs::Info_<ContainerAllocator1> & lhs, const ::qb_device_msgs::Info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qb_device_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qb_device_msgs::Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qb_device_msgs::Info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qb_device_msgs::Info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qb_device_msgs::Info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qb_device_msgs::Info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qb_device_msgs::Info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qb_device_msgs::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee93ec9c1a360ac561916c3deecf8486";
  }

  static const char* value(const ::qb_device_msgs::Info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee93ec9c1a360ac5ULL;
  static const uint64_t static_value2 = 0x61916c3deecf8486ULL;
};

template<class ContainerAllocator>
struct DataType< ::qb_device_msgs::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qb_device_msgs/Info";
  }

  static const char* value(const ::qb_device_msgs::Info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qb_device_msgs::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Standard device-independent info message\n"
"\n"
"int32 id\n"
"string serial_port\n"
"int32 max_repeats\n"
"bool get_positions\n"
"bool get_currents\n"
"bool get_distinct_packages\n"
"bool set_commands\n"
"bool set_commands_async\n"
"int32[] position_limits\n"
"uint8[] encoder_resolutions\n"
;
  }

  static const char* value(const ::qb_device_msgs::Info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qb_device_msgs::Info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.serial_port);
      stream.next(m.max_repeats);
      stream.next(m.get_positions);
      stream.next(m.get_currents);
      stream.next(m.get_distinct_packages);
      stream.next(m.set_commands);
      stream.next(m.set_commands_async);
      stream.next(m.position_limits);
      stream.next(m.encoder_resolutions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qb_device_msgs::Info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qb_device_msgs::Info_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "serial_port: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.serial_port);
    s << indent << "max_repeats: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_repeats);
    s << indent << "get_positions: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_positions);
    s << indent << "get_currents: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_currents);
    s << indent << "get_distinct_packages: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_distinct_packages);
    s << indent << "set_commands: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_commands);
    s << indent << "set_commands_async: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_commands_async);
    s << indent << "position_limits[]" << std::endl;
    for (size_t i = 0; i < v.position_limits.size(); ++i)
    {
      s << indent << "  position_limits[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.position_limits[i]);
    }
    s << indent << "encoder_resolutions[]" << std::endl;
    for (size_t i = 0; i < v.encoder_resolutions.size(); ++i)
    {
      s << indent << "  encoder_resolutions[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.encoder_resolutions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QB_DEVICE_MSGS_MESSAGE_INFO_H
